### ISSUE TITLE
PHP

### ISSUE THREAD

**Issue by berkcantasan** [oguzzkilic/ama#10]
Merhabalar. Bir konuda bilgi almak istiyordum. Şimdi ben form-anket karışımı bir php site yaptım doldurulan bilgiler sqle kaydedilince excel formuna çevirip bilgisayara indiriyor fakat ben bu çevirilen excel formunu indirmek yerine belli bir mail adresine yönlendirmek istiyorum bu mümkün mü acaba? Cevaplarsanız çok sevinirim. İyi günler

**Comment by oguzzkilic** [comment]
Php bilgi alanımda değil maalesef. Cevap için Google'a veya Php bilen birisine sormanızı tavsiye ederim :)

**Comment by yusufonur** [comment]
Excell dosyayı sunucunuzda tmp bir dosyaya kaydedip ilgili url i alarak smtp ile istediğiniz kişiye indirme url veya mail ek i olarak gönderebilirsiniz.

smtp örneği için bu github sayfasını ziyaret edebilirsiniz = https://github.com/alchemy-fr/PHPMailer_v5.1 

Örnek bir kod blogu:

`<?php
require("class.phpmailer.php");
$mail = new PHPMailer(); // create a new object
$mail->IsSMTP(); // enable SMTP
$mail->SMTPDebug = 1; // debugging: 1 = errors and messages, 2 = messages only
$mail->SMTPAuth = true; // authentication enabled
$mail->SMTPSecure = 'ssl'; // secure transfer enabled REQUIRED for GMail
$mail->Host = "smtp.yandex.com";
$mail->Port = 465; // or 587
$mail->IsHTML(true);
$mail->SetLanguage("tr", "phpmailer/language");
$mail->CharSet  ="utf-8";

$mail->Username = "gonderici@mail.com"; // Mail adresi
$mail->Password = "mailParolasi"; // Parola
$mail->SetFrom("gonderici@mail.com", "Gönderici Adı"); // Mail adresi

$mail->AddAddress("alici@mail.com"); // Gönderilecek kişi

$mail->Subject = "Mesaj başlığı";
$mail->Body = "buraya da mesaj içeriğini koyuyoruz. Excell linki burada olabilir.";

if(!$mail->Send()){
                echo "Mailer Error: ".$mail->ErrorInfo;
} else {
                echo "Message has been sent";
}

?>`


Eğer ben excel dosyamı mail e attachment edeceğim diyorsanız bu sayfaya bakabilirsiniz = https://stackoverflow.com/questions/3299577/php-how-to-send-email-with-attachment-using-smtp-settings
